version: '3'
services:
  web:
    container_name: cltw_web
    build: .
    volumes:
      - ./web:/var/www/html/cltw
    ports:
      - 8081:8081
      - 3000:3000
  db:
    container_name: cltw_db
    image: mysql:5.6.47
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: cltw
    volumes:
      - ./database:/var/lib/mysql/data
    ports:
      - 3306:3306