version: '3'
services:
  cltw_web:
    build: .
    volumes:
      - ./web:/var/www/html/cltw
    ports:
      - 8081:8081
      - 3000:3000
  cltw_db:
    image: mysql:5.7.29
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./database:/var/lib/mysql/data
    ports:
      - 5434:5432